
services:
  nginx:
    image: nginx:1.19.5-alpine
    depends_on: [orthanc]
    restart: always
    ports: ["${ORTHANC_WEB_PORT}:80"]
    # networks:
    #   - frontend
    #   - backend
    volumes:
      # Nginx as a reversed proxy for orthanc and the viewer
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=Europe/Paris
    logging:
        driver: "json-file"
        options:
            max-size: "10m"

  orthanc:
    # image: orthancteam/orthanc
    build: orthanc
    depends_on: [index-db]
    restart: always
    ports: ["${ORTHANC_AET_PORT}:${ORTHANC_AET_PORT}", "8042:8042"]
    volumes:
      ## Storage volumes to be customised 
      # Storage volume for raw dicoms
      - ${ORTAHNC_DB_STORAGE_PATH}:/var/lib/orthanc/db
      # Storage for Automation
      - ${ORTHANC_AUTOMATION_JSON_SCRIPTS_PATH}:/automation_scripts:rw
      - ${ORTHANC_AUTOMATION_STORAGE_PATH}:/automation_output:rw
    environment:
      ## Environment variables for customisation:
      ORTHANC__NAME: ${ORTHANC_DISPLAY_NAME}
      ORTHANC__DICOM_AET: ${ORTHANC_AET_NAME}
      ORTHANC__DICOM_PORT: ${ORTHANC_AET_PORT} 
      ORTHANC__REGISTERED_USERS: |
        {"autorthanc": "autorthanc"}
      ORTHANC__STABLE_AGE: ${ORTHANC_STABLE_AGE}
      ORTHANC__DICOM_MODALITIES: ${ORTHANC_DICOM_MODALITIES}
      
      ORTHANC__AUTHENTICATION_ENABLED: ${ORTHANC_AUTHENTICATION_ENABLED}
      ORTHANC__DICOM_SCP_TIMEOUT: 120
      ORTHANC__DICOM_SCU_TIMEOUT: 120
      ORTHANC__CONCURRENT_JOBS: 32
      ORTHANC__MAXIMUM_STORAGE_CACHE_SIZE: 4096
      ORTHANC__HTTP_REQUEST_TIMEOUT: 120 

      ##
      PYTHON_PLUGIN_ENABLED: "true"
      ORTHANC__PYTHON_SCRIPT: "/scripts/automation.py"
      ORTHANC__PYTHON_VERBOSE: "true"
      ##
      ## POSTGRES
      ORTHANC__POSTGRESQL__HOST: "index-db"
      ORTHANC__POSTGRESQL__DATABASE: "postgres"
      ORTHANC__POSTGRESQL__USERNAME: "postgres"
      ORTHANC__POSTGRESQL__PASSWORD: "postgres"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      ORTHANC__POSTGRESQL__ENABLE_STORAGE: "false"
      ##
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      # DICOMWeb Plugin
      DICOM_WEB_PLUGIN_ENABLED: "true"
      # ORTHANC_WEB Plugin
      ORTHANC_WEB_VIEWER_PLUGIN_ENABLED: "true"
      # STONE_WEB Plugin
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      # Postgres Plugin
      POSTGRESQL_PLUGIN_ENABLED: "true"
      # OrthancExplorer2
      ORTHANC_EXPLORER_2_ENABLED: "true"
      ORTHANC_EXPLORER_2__IS_DEFAULT_ORTHANC_UI: "true"
      ##
    logging:
        driver: "json-file"
        options:
            max-size: "10m"

  index-db:
    image: postgres
    restart: always
    ports: ["${POSGRES_DOCKER_EXPOSE_PORT}:5432"]
    volumes: ["orthanc-index:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "postgres"
    logging:
        driver: "json-file"
        options:
            max-size: "10m"

volumes:
  orthanc-index:
